### ISSUE TITLE
Missing FFImageLoading Init Part in Android

### ISSUE THREAD

**Issue by hussamelvani** [sthewissen/iBakePancakes#1]
Hey,
I have just tried your iBakePancakes sample app and it looks amazing! thanks for your work.
However, when I tried to run the app using Android, it threw an initialization error. I added the following and it works like it should.
`FFImageLoading.Forms.Platform.CachedImageRenderer.Init(enableFastRenderer: [true]/[false]);`
I can create a PR if you are busy and cannot edit it.
#2

**Comment by sthewissen** [comment]
Yeah feel free, I'll gladly accept it. For me this is not much more than a sample app that I pretty much exclusively tested on iOS :)
